Create human player
KrystianKjjk/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #28
Opened 2021-01-10 13:45 UTC by juliakozlowska

https://github.com/CodersCamp2020/CodersCamp2020.Project.JavaScript.StarWarsQuiz/issues/20

Proszę o code review.

2021-01-10 15:48 UTC, kjreczek approved these changes
👍

2021-01-11 07:55 UTC, robert-czwartosz approved these changes

2021-01-11 08:00 UTC, robert-czwartosz requested changes
Julia, if you resolve confilcts, I will approve and merge this pull request.

2021-01-11 19:49 UTC, robert-czwartosz approved these changes

2021-01-11 19:49 UTC, merged